#!/usr/bin/env python
# $Id$

import sys
from Yogurt.Commands import dependency
err = dependency.check()
if err:
    print >> sys.stderr, err
    raise SystemExit

from Yogurt.Commands import yogurt
yogurt.main()
